#cloud-config
chpasswd:
  expire: false
  list: |
    root:{{ tmos_root_password }}
    admin:{{ tmos_admin_password }}
ssh_authorized_keys:
  - {{ tmos_root_authorized_ssh_key }}
tmos_declared:
  enabled: true
  icontrollx_trusted_sources: false
  icontrollx_package_urls:
    - {{ do_url }}
    - {{ as3_url }}
  do_declaration:
    schemaVersion: 1.0.0
    class: Device
    async: true
    label: Cloudinit Onboarding
    Common:
      class: Tenant
      hostname: {{ hostname_secondary }}
      provisioningLevels:
        class: Provision
        ltm: nominal
      poolLicense:
        class: License
        licenseType: licensePool
        bigIqHost: {{ license_host }}
        bigIqUsername: {{ license_username }}
        bigIqPassword: {{ license_password }}
        licensePool: {{ license_pool }}
        reachable: false
        hypervisor: kvm
      dnsServers:
        class: DNS
        nameServers:
          - {{ dns_server }}
        search:
          - {{ search_domain }}
      ntpServers:
        class: NTP
        servers:
          - 0.pool.ntp.org
          - 1.pool.ntp.org
          - 2.pool.ntp.org
      HA:
        class: VLAN
        mtu: {{ cluster_mtu_secondary }}
        interfaces:
          - name: 1.1
            tagged: false
      HA-self:
        class: SelfIp
        address: "{{ cluster_selfip_secondary }}/{{ cluster_mask_secondary }}"
        vlan: HA
        allowService: all
        trafficGroup: traffic-group-local-only
      configsync:
        class: ConfigSync
        configsyncIp: /Common/HA-self/address
      failoverAddress:
        class: FailoverUnicast
        address: /Common/HA-self/address
      external:
        class: VLAN
        mtu: {{ vip_mtu_secondary }}
        interfaces:
          - name: 1.2
            tagged: false
      external-self:
        class: SelfIp
        address: "{{ vip_selfip_secondary }}/{{ vip_mask_secondary }}"
        vlan: external
        allowService: none
        trafficGroup: traffic-group-local-only
      default:
        class: Route
        gw: {{ default_gateway_secondary }}
        network: default
        mtu: {{ vip_mtu_secondary }}
      dbvars:
        class: DbVariables
        ui.advisory.enabled: true
        ui.advisory.color: orange
        ui.advisory.text: This device is under centralized management.
      activeStandbyGroup:
        class: DeviceGroup
        type: sync-failover
        owner: {{ hostname_secondary }}
        members:
          - {{ hostname_primary }}
          - {{ hostname_secondary }}
        autoSync: false
        networkFailover: true
        saveOnAutoSync: false
        fullLoadOnSync: false
        asmSync: false
      trust:
        class: DeviceTrust
        localUsername: admin
        localPassword: {{ tmos_admin_password }}
        remoteHost: {{ secondary_cluster_ip }}
        remoteUsername: admin
        remotePassword: {{ tmos_admin_password }}
  as3_enabled: false
  post_onboard_enabled: false
  phone_home_url: "{{ phone_home_url }}"
bootcmd:
  - "printf \"platform=Z100\\nfamily=0xC000000\\nhost=Z100\\nsystype=0x71\\n\">/PLATFORM"