#cloud-config
chpasswd:
  expire: false
  list: |
    root:$root_password
    admin:$admin_password
tmos_configdrive_openstack:
  enabled: true
  rd_enabled: false
  configsync_interface: 1.1
  default_route_interface: 1.2
  inject_routes: true
  icontrollx_trusted_sources: false
  icontrollx_package_urls:
    - $do_url
    - $as3_url
  do_enabled: true
  do_declaration:
    schemaVersion: 1.0.0
    class: Device
    async: true
    label: Cloudinit Onboarding
    Common:
      class: Tenant
      hostname: primary-adc-instance.local
      provisioningLevels:
        class: Provision
        ltm: nominal
      poolLicense:
        class: License
        licenseType: licensePool
        bigIqHost: $license_host
        bigIqUsername: $license_username
        bigIqPassword: $license_password
        licensePool: $license_pool
        reachable: true
        bigIpUsername: admin
        bigIpPassword: $admin_password
      dbvars:
        class: DbVariables
        ui.advisory.enabled: true
        ui.advisory.color: orange
        ui.advisory.text: This device is under centralized management.
      activeStandbyGroup:
        class: DeviceGroup
        type: sync-failover
        owner: secondary-adc-instance.local
        members:
          - primary-adc-instance.local
          - secondary-adc-instance.local
        autoSync: false
        networkFailover: true
        saveOnAutoSync: false
        fullLoadOnSync: false
        asmSync: false
      trust:
        class: DeviceTrust
        localUsername: admin
        localPassword: $admin_password
        remoteHost: $secondary_cluster_ip
        remoteUsername: admin
        remotePassword: $admin_password
  as3_enabled: false
  phone_home_url: "$phone_home_url"
  phone_home_cli: "$wc_notify"
  post_onboard_enabled: true
  post_onboard_commands:
    - tmsh run cm config-sync to-group activeStandbyGroup
bootcmd:
  - "printf \"platform=Z100\\nfamily=0xC000000\\nhost=Z100\\nsystype=0x71\\n\">/PLATFORM"