#cloud-config
chpasswd:
  expire: false
  list: |
    root:$root_password
    admin:$admin_password
ssh_authorized_keys:
  - $root_ssh_key
tmos_declared:
  enabled: true
  icontrollx_trusted_sources: false
  icontrollx_package_urls:
    - $do_url
    - $as3_url
  do_declaration:
    schemaVersion: 1.0.0
    class: Device
    async: true
    label: Cloudinit Onboarding
    Common:
      class: Tenant
      provisioningLevels:
        class: Provision
        ltm: nominal
      poolLicense:
        class: License
        licenseType: licensePool
        bigIqHost: $license_host
        bigIqUsername: $license_username
        bigIqPassword: $license_password
        licensePool: $license_pool
        reachable: true
        bigIpUsername: admin
        bigIpPassword: $admin_password
      dnsServers:
        class: DNS
        nameServers:
          - $dns_server
        search:
          - example.openstack.com
      ntpServers:
        class: NTP
        servers:
          - 0.pool.ntp.org
          - 1.pool.ntp.org
          - 2.pool.ntp.org
      configsync:
        class: ConfigSync
        configsyncIp: /Common/external-self/address
      failoverAddress:
        class: FailoverUnicast
        address: /Common/external-self/address
      external:
        class: VLAN
        mtu: $vip_mtu
        interfaces:
          - name: 1.1
            tagged: false
      external-self:
        class: SelfIp
        address: $vip_selfip/$vip_mask
        vlan: external
        allowService: none
        trafficGroup: traffic-group-local-only
      default:
        class: Route
        gw: $default_gateway
        network: default
        mtu: $vip_mtu
      dbvars:
        class: DbVariables
        ui.advisory.enabled: true
        ui.advisory.color: orange
        ui.advisory.text: This device is under centralized management.
  as3_enabled: false
  phone_home_url: "$phone_home_url"
  phone_home_cli: "$wc_notify"
bootcmd:
  - "printf \"platform=Z100\\nfamily=0xC000000\\nhost=Z100\\nsystype=0x71\\n\">/PLATFORM"