################################################################################
#
# F5 Heat Template to Orchestrate a 3 NIC TMOS WAF
#
#    Management Network
# ------------------------------ License Activation with BIG-IQ
#           |
#     eth0  |    HA Network
#        -------      |
#        | VE  | 1.1  |        TMM 1.1 - HA Interface
#        |     |   ---|        TMM 1.2 - Date Network
#        -------      |
# 1.2       |
# ------------------------------
#    Data Network
#
################################################################################
heat_template_version: 2015-10-15

description: F5 Heat Template to Orchestrate a 3 NIC TMOS WAF

parameters:
  tmos_image:
    type: string
    label: TMOS VE Disk Image
    description: The image to be used on the TMOS VE instance.
    constraints:
      - custom_constraint: glance.image
  tmos_flavor:
    type: string
    label: TMOS VE Flavor
    description: Type of instance (flavor) to be used for the TMOS VE instance.
    default: m1.bigip.ALL.1SLOT
    constraints:
      - custom_constraint: nova.flavor
  tmos_root_authkey_name:
    type: string
    label: TMOS Root SSH Authkey name
    description: The name of the OpenStack Authkey to ue for the root user
    default: admin
  tmos_root_password:
    type: string
    label: TMOS Root Password
    description: Password to set for the built-in root user
    default: f5c0nfig
    hidden: true
  tmos_admin_password:
    type: string
    label: TMOS Administrator Password
    description: Password to set for the built-in admin user
    default: f5c0nfig
    hidden: true
  license_host:
    type: string
    label: BIG-IQ Licensor Host
    description: BIG-IQ IP or hostname to license TMOS VE instance
    default: None
  license_username:
    type: string
    label: BIG-IQ User
    description: BIG-IQ user name
    default: admin
  license_password:
    type: string
    hidden: true
    label: BIG-IQ Password
    description: BIG-IQ password
    default: admin
  license_pool:
    type: string
    label: BIG-IQ License Pool
    description: BIG-IQ license pool for this TMOS VE instance
    default: None
  do_url:
    type: string
    label: DO URL
    description: f5-declarative-onboarding package URL
  as3_url:
    type: string
    label: AS3 URL
    description: f5-appsvcs-extension package URL
  waf_policy_url:
    type: string
    label: WAF Policy URL
    description: URL for the TMOS ASM Policy XML Template
    default: https://raw.githubusercontent.com/f5devcentral/f5-asm-policy-template-v13/master/owasp_ready_template/v1/ASMv131/owasp-no-auto-tune-v131.xml
  phone_home_url:
    type: string
    label: Phone Home URL
    description: URL for the phone home when onboarding finishes
    default: https://webhook.site/
  external_network:
    type: string
    label: External Access Network
    description: The network to assign Floating IPs for management access
    default: None
    constraints:
      - custom_constraint: neutron.network
  management_network:
    type: string
    label: Management Network
    description: OAM Network
    default: None
    constraints:
      - custom_constraint: neutron.network
  management_network_security_group:
    type: string
    label: Management Network Security Group
    description: OAM Network Security Group
    default: default
  cluster_network:
    type: string
    label: Cluster Network
    description: HA Cluster Sync Network
    default: None
    constraints:
      - custom_constraint: neutron.network
  cluster_network_security_group:
    type: string
    label: Cluster Network Security Group
    description: HA Cluster Sync Network Security Group
    default: default
  vip_network:
    type: string
    label: Virtual Servers Network
    description: Virtual Servers Network for Client Traffic
    default: None
    constraints:
      - custom_constraint: neutron.network
  vip_network_security_group:
    type: string
    label: Virtual Servers Network Security Group
    description: Virtual Servers Network for Client Traffic Security Group
    default: default
  vip_subnet:
    type: string
    label: Virtual Servers Subnet
    description: Virtual Servers Subnet for Client Virtual Servers
    constraints:
      - custom_constraint: neutron.subnet
  heat_timeout:
    type: number
    label: Heat Stack Timeout
    description: The Heat stack timeout in seconds
    default: 1800

parameter_groups:
- parameters:
  - tmos_image
  - tmos_flavor
- parameters:
  - tmos_root_authkey_name
  - tmos_root_password
  - tmos_admin_password
- parameters:
  - license_host
  - license_username
  - license_password
  - license_pool
- parameters:
  - do_url
  - as3_url
- parameters:
  - waf_policy_url
  - phone_home_url
- parameters:
  - external_network
  - management_network
  - management_network_security_group
  - cluster_network
  - cluster_network_security_group
  - vip_network
  - vip_network_security_group
  - vip_subnet
- parameters:
  - heat_timeout

resources:
  tmos_mgmt_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: management_network }
      security_groups:
        - { get_param: management_network_security_group }
      allowed_address_pairs:
        - ip_address: 0.0.0.0/0
        - ip_address: ::/0
  tmos_mgmt_floating_ip:
    type: OS::Neutron::FloatingIP
    depends_on: tmos_mgmt_port
    properties:
      floating_network: { get_param: external_network }
      port_id: { get_resource: tmos_mgmt_port }
  tmos_cluster_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: cluster_network }
      security_groups:
        - { get_param: cluster_network_security_group }
      allowed_address_pairs:
        - ip_address: 0.0.0.0/0
        - ip_address: ::/0
  tmos_vip_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: vip_network }
      security_groups:
        - { get_param: vip_network_security_group }
      allowed_address_pairs:
        - ip_address: 0.0.0.0/0
        - ip_address: ::/0
      fixed_ips:
        - subnet: { get_param: vip_subnet }
        - subnet: { get_param: vip_subnet }
  service_floating_ip:
    type: OS::Neutron::FloatingIP
    depends_on: tmos_vip_port
    properties:
      floating_network: { get_param: external_network }
      port_id: { get_resource: tmos_vip_port }
      fixed_ip_address: { get_attr: [ tmos_vip_port, fixed_ips, 0, ip_address ] }
  wait_handle:
    type: OS::Heat::WaitConditionHandle
  wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: { get_resource: wait_handle }
      timeout: { get_param: heat_timeout }
  waf_instance:
    type: OS::Nova::Server
    depends_on: [tmos_mgmt_port, tmos_cluster_port, tmos_vip_port]
    properties:
      image: { get_param: tmos_image }
      flavor: { get_param: tmos_flavor }
      config_drive: true
      key_name: { get_param: tmos_root_authkey_name }
      networks:
        - port: { get_resource: tmos_mgmt_port }
        - port: { get_resource: tmos_cluster_port }
        - port: { get_resource: tmos_vip_port }
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            $root_password: { get_param: tmos_root_password }
            $admin_password: { get_param: tmos_admin_password }
            $license_host: { get_param: license_host }
            $license_username: { get_param: license_username }
            $license_password: { get_param: license_password }
            $license_pool: { get_param: license_pool }
            $do_url: { get_param: do_url }
            $as3_url: { get_param: as3_url }
            $waf_vip: { get_attr: [ tmos_vip_port, fixed_ips, 0, ip_address ] }
            $waf_policy_url: { get_param: waf_policy_url }
            $phone_home_url: { get_param: phone_home_url }
            $wc_notify: { get_attr: ['wait_handle', 'curl_cli'] }
          template: { get_file: 'user_data.yaml' }
outputs:
  tmos_management_xui_private:
    description: TMOS management service IP address
    value: { list_join: ['', ['https://', { get_attr: [ tmos_mgmt_port, fixed_ips, 0, ip_address ] } ]] }
  tmos_management_cli_private:
    description: TMOS management service IP address
    value: { list_join: ['', ['ssh://root@', { get_attr: [ tmos_mgmt_port, fixed_ips, 0, ip_address ] } ]] }
  tmos_management_xui_public:
    description: Floating IP access the TMOS management services
    value: { list_join: ['', ['https://', { get_attr: [ tmos_mgmt_floating_ip, floating_ip_address ] } ]] }
  tmos_management_cli_public:
    description: TMOS management service IP address
    value: { list_join: ['', ['ssh://root@', { get_attr: [ tmos_mgmt_floating_ip, floating_ip_address ] } ]] }
  f5_declarative_onboarding_private:
    description: Device Level Declarative REST API
    value: { list_join: ['', ['https://', { get_attr: [ tmos_mgmt_port, fixed_ips, 0, ip_address ] }, '/mgmt/shared/declarative-onboarding' ]] }
  f5_appsvcs_extension_private:
    description: Service Level Declarative REST API
    value: { list_join: ['', ['https://', { get_attr: [ tmos_mgmt_port, fixed_ips, 0, ip_address ] }, '/mgmt/shared/appsvcs/declare' ]] }
  f5_declarative_onboarding_public:
    description: Device Level Declarative REST API
    value: { list_join: ['', ['https://', { get_attr: [ tmos_mgmt_floating_ip, floating_ip_address ] }, '/mgmt/shared/declarative-onboarding' ]] }
  f5_appsvcs_extension_public:
    description: Service Level Declarative REST API
    value: { list_join: ['', ['https://', { get_attr: [ tmos_mgmt_floating_ip, floating_ip_address ] }, '/mgmt/shared/appsvcs/declare' ]] }
  tmos_waf:
    description: TMOS Virtual Server
    value: { list_join: ['', ['http://', { get_attr: [ service_floating_ip, floating_ip_address ] } ]] }
  tmos_phone_home_url:
    description: Phone Home URL
    value: { get_param: phone_home_url }
  heat_phone_home_cli:
    description: Heat Wait Condition CLI
    value: { get_attr: ['wait_handle', 'curl_cli'] }

