---

- hosts: all
  name: TMOS VE Instance
  tasks:
    - include_vars:
        file: config.yaml
    - include_role:
        name: networks
    - include_role:
        name: configdrive
    - include_role:
        name: domain
