parameters:
  tmos_image: e8834ef4-b262-4798-aa03-8fe4da35daef
  tmos_flavor: df6c0550-14fe-4a0e-b08b-9c397c0c1fe2
  tmos_root_password: f5c0nfig
  tmos_admin_password: f5c0nfig
  license_host: 192.168.245.114
  license_username: admin
  license_password: admin
  license_pool: BIGIPVEREGKEYS
  waf_policy_url: https://raw.githubusercontent.com/f5devcentral/f5-asm-policy-template-v13/master/owasp_ready_template/v1/ASMv131/owasp-no-auto-tune-v131.xml
  # monitor at: https://webhook.site/#!/7af00208-313d-42e9-b0f9-d0e88d631989/2a06b288-fd01-4f1c-a33e-097ef81712cb/1
  phone_home_url: https://webhook.site/7af00208-313d-42e9-b0f9-d0e88d631989
  external_network: 9c74eb83-ae4d-4b51-82fa-df0084cc8f6b
  management_network: d0a2306c-31bb-46ef-8abf-6b622639c01a
  cluster_network: e185645b-7fbd-4b2b-9ea1-a551fed55cb6
  vip_network: 5eaa04e7-efe1-47e9-a6a4-dad7e5465f32
  vip_subnet: 55ff861a-1dbf-45b4-b7b8-31006f1f9f20
  heat_timeout: 1800
