parameters:
  tmos_image: 26f8666b-e226-4754-9ae2-29eef41543af
  tmos_flavor: 61b6b513-4a74-4d8d-8365-a7b712b40aa0
  tmos_root_password: f5c0nfig
  tmos_admin_password: f5c0nfig
  license_host: 192.168.245.114
  license_username: admin
  license_password: admin
  license_pool: BIGIPVEREGKEYS
  do_url: https://github.com/F5Networks/f5-declarative-onboarding/releases/download/v1.5.0/f5-declarative-onboarding-1.5.0-11.noarch.rpm
  as3_url: https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.12.0/f5-appsvcs-3.12.0-5.noarch.rpm
  # monitor at: https://webhook.site/#!/7af00208-313d-42e9-b0f9-d0e88d631989/2a06b288-fd01-4f1c-a33e-097ef81712cb/1
  phone_home_url: https://webhook.site/7af00208-313d-42e9-b0f9-d0e88d631989
  external_network: 9c74eb83-ae4d-4b51-82fa-df0084cc8f6b
  management_network: d0a2306c-31bb-46ef-8abf-6b622639c01a
  cluster_network: e185645b-7fbd-4b2b-9ea1-a551fed55cb6
  internal_network: 8b1cf4ca-012d-4164-ae7d-68e2670caf7a
  vip_network: 5eaa04e7-efe1-47e9-a6a4-dad7e5465f32
  vip_subnet: 55ff861a-1dbf-45b4-b7b8-31006f1f9f20
  heat_timeout: 1800
