parameters:
  tmos_image: 24776b05-56fc-43c8-9ad9-928f12538053
  tmos_flavor: 8d2a3385-6ec5-4281-926e-7f6814f1f1fd
  tmos_root_password: f5c0nfig
  tmos_admin_password: f5c0nfig
  license_host: 192.168.245.114
  license_username: admin
  license_password: admin
  license_pool: BIGIPVEREGKEYS
  do_url: https://github.com/F5Networks/f5-declarative-onboarding/releases/download/v1.5.0/f5-declarative-onboarding-1.5.0-11.noarch.rpm
  as3_url: https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.12.0/f5-appsvcs-3.12.0-5.noarch.rpm
  waf_policy_url: https://raw.githubusercontent.com/f5devcentral/f5-asm-policy-templates/master/owasp_ready_template/owasp-no-auto-tune-v1.1.xml
  # monitor at: https://webhook.site/#!/92a65a6f-0cd8-4bea-ab83-79df26c565f4
  phone_home_url: https://webhook.site/92a65a6f-0cd8-4bea-ab83-79df26c565f4
  external_network: 8fbbf835-806a-46b7-8e63-1d10866d0ffe
  management_network: 628a623d-b189-4a4e-b942-cfde22f88537
  cluster_network: c37fbf04-da8a-42c5-8cd0-25d2228f22f2
  vip_network: 75f7f27b-da13-4042-ac22-3706d389d3c5
  vip_subnet: f7ca6648-484f-4e8a-8fe5-99d273d7fc38
  heat_timeout: 1800
