---
- name: create_tmos_mgmt_port
  os_port:
    state: present
    name: "{{ server_name }}_management_port"
    network: "{{ management_network }}"
    security_groups:
      - "{{ management_network_security_group }}"
    allowed_address_pairs:
      - ip_address: 0.0.0.0/0
      - ip_address: ::/0
  register: tmos_mgmt_port
- name: create_tmos_vip_port
  os_port:
    state: present
    name: "{{ server_name }}_vip_port"
    network: "{{ vip_network }}"
    security_groups:
      - "{{ vip_network_security_group }}"
    allowed_address_pairs:
      - ip_address: 0.0.0.0/0
      - ip_address: ::/0
    fixed_ips:
      - subnet_id: "{{ vip_subnet }}"
      - subnet_id: "{{ vip_subnet }}"
  register: tmos_vip_port
- set_fact:
    waf_vip: "{{ tmos_vip_port.port.fixed_ips.0.ip_address }}"
- name: create_adc_instance
  os_server:
    state: present
    name: "{{ server_name }}"
    image: "{{ tmos_image }}"
    flavor: "{{ tmos_flavor }}"
    auto_ip: no
    config_drive: yes
    key_name: "{{ tmos_root_authkey_name }}"
    nics:
      - port-id: "{{ tmos_mgmt_port.id }}"
      - port-id: "{{ tmos_vip_port.id }}"
    userdata: "{{ lookup('template', './user_data.yaml') }}"
    wait: yes
  register: adc_instance
- name: create_tmos_mgmt_floating_ip
  os_floating_ip:
    state: present
    reuse: yes
    server: "{{ adc_instance.id }}"
    network: "{{ external_network }}"    
    nat_destination: "{{ management_network }}"
    fixed_address: "{{ tmos_mgmt_port.port.fixed_ips.0.ip_address }}"
    wait: yes
  register: tmos_mgmt_floating_ip
#- name: create_service_floating_ip
  # see https://github.com/ansible/ansible/issues/60193
  # Our friends at Red Hat decided to create their 
  # own OpenStack client called shade. When creating
  # the os_floatingip module, they didn't bother to 
  # think anyone would ever want more than one floating_ip. 
  # Call your Red Hat SE and ask why they don't like Neutron.
  #
  # We'll just let Neutron be Neutron and make our own REST
  # request to create the secondary floatingip.
  #
  #os_floating_ip:
  # state: present
  # server: "{{ adc_instance.id }}"
  # network: "{{ external_network }}"
  # fixed_address: "{{ waf_vip }}"
  # wait: yes
  #register: service_floating_ip
  #
- name: get_auth_token
  os_auth:
    wait: yes
- name: discover_network_endpoint
  set_fact: 
    neutron_url: "{{ service_catalog | json_query(lsc) | json_query(lep) | first | first }}"
  vars:
    - lsc: "[?name == 'neutron'].endpoints[*]"
    - lep: "[*][?interface == 'public'].url"
- debug:
    var: neutron_url
- name: query_for_existing_sevice_floating_ip
  uri:
    url: "{{ neutron_url }}/v2.0/floatingips?project_id={{ tmos_vip_port.port.project_id }}&fixed_ip_address={{ waf_vip }}&floating_network_id={{ external_network }}"
    headers:
      X-Auth-Token: "{{ auth_token }}"
      Content-Type: application/json
    method: GET
    body_format: json
    status_code: 200
    return_content: yes
  register: existing_service_fip
- debug:
    var: existing_service_fip 
- name: set_existing_service_fip_facts
  set_fact:
    service_floating_ip_address: "{{ existing_service_fip.json.floatingips.0.floating_ip_address }}"
    service_floating_ip_id: "{{ existing_service_fip.json.floatingips.0.id }}"
  when: existing_service_fip.json.floatingips | length > 0 
- name: get_all_floatingips_on_net
  uri:
    url: "{{ neutron_url }}/v2.0/floatingips?project_id={{ tmos_vip_port.port.project_id }}&floating_network_id={{ external_network }}"
    headers:
      X-Auth-Token: "{{ auth_token }}"
      Content-Type: application/json
    method: GET
    body_format: json
    status_code: 200
    return_content: yes
  register: all_floatingips_on_net
  when: service_floating_ip_address is not defined
- name: select_floating_ip
  set_fact:
    selected_floating_ip: "{{ item }}"
  with_items: "{{ all_floatingips_on_net.json.floatingips }}"
  when: 
    - service_floating_ip_address is not defined
    - not item.fixed_ip_address
- name: create_service_floating_ip
  uri:
    url: "{{ neutron_url }}/v2.0/floatingips"
    headers:
      X-Auth-Token: "{{ auth_token }}"
      Content-Type: application/json
    method: POST
    body:
      floatingip:
        floating_network_id: "{{ external_network }}"
        port_id: "{{ tmos_vip_port.id }}"
        fixed_ip_address: "{{ waf_vip }}"
    body_format: json
    status_code: 200, 201
  register: fip_result
  when: 
    - service_floating_ip_address is not defined
    - selected_floating_ip is not defined
- name: set_service_floatingip_fact_from_created_floatingip
  set_fact:
    service_floating_ip_address: "{{ fip_result.json.floatingip.floating_ip_address }}"
    service_floating_ip_id: "{{ fip_result.json.floatingip.id }}"
  when: 
    - service_floating_ip_address is not defined
    - selected_floating_ip is not defined
- name: associate_service_floating_ip
  uri:
    url: "{{ neutron_url }}/v2.0/floatingips/{{ selected_floating_ip.id }}"
    headers:
      X-Auth-Token: "{{ auth_token }}"
      Content-Type: application/json
    method: PUT
    body:
      floatingip:
        port_id: "{{ tmos_vip_port.id }}"
        fixed_ip_address: "{{ waf_vip }}"
    body_format: json
    status_code: 200, 201
  register: fip_result
  when: 
    - service_floating_ip_address is not defined
    - selected_floating_ip is defined
- name: set_service_floatingip_fact_from_associated_floatingip
  set_fact:
    service_floating_ip_address: "{{ fip_result.json.floatingip.floating_ip_address }}"
    service_floating_ip_id: "{{ fip_result.json.floatingip.id }}"
  when: 
    - service_floating_ip_address is not defined
    - selected_floating_ip is defined

- debug:
    msg: "TMOS management private web UI: https://{{ tmos_mgmt_port.port.fixed_ips.0.ip_address }}"
- debug:
    msg: "TMOS management private console: ssh://root@{{ tmos_mgmt_port.port.fixed_ips.0.ip_address }}"
- debug:
    msg: "TMOS management public web UI: https://{{ tmos_mgmt_floating_ip.floating_ip.floating_ip_address }}"
- debug:
    msg: "TMOS management public console: ssh://root@{{ tmos_mgmt_floating_ip.floating_ip.floating_ip_address }}"
- debug:
    msg: "Declarative Onboarding private URL: https://{{ tmos_mgmt_port.port.fixed_ips.0.ip_address }}/mgmt/shared/declarative-onboarding"
- debug:
    msg: "App Services private URL: https://{{ tmos_mgmt_port.port.fixed_ips.0.ip_address }}/mgmt/shared/appsvcs/declare"
- debug:
    msg: "Declarative Onboarding public URL: https://{{ tmos_mgmt_floating_ip.floating_ip.floating_ip_address }}/mgmt/shared/declarative-onboarding"
- debug:
    msg: "App Services public URL: https://{{ tmos_mgmt_floating_ip.floating_ip.floating_ip_address }}/mgmt/shared/appsvcs/declare"
- debug:
    msg: "WAF Virtual Service private: http://{{ waf_vip }}"
- debug:
    msg: "WAF Virtual Server public: http://{{ service_floating_ip_address }}"
- debug:
    msg: "Phone home URL: {{ phone_home_url }}"