---
# tasks file for networks
- name: Define HA Network
  when: assure_libvirt_networks
  tags: networks
  virt_net:
    uri: "{{ libvirt_connect_string }}"
    autostart: yes
    command: define
    name: ha
    xml: '{{ lookup("template", "ha_network.xml.j2") }}'
  register: ha_network_defined
- name: Activate HA Network
  when: 
    - assure_libvirt_networks
    - ha_network_defined
  tags: networks
  virt_net:
    uri: "{{ libvirt_connect_string }}"
    command: start
    state: active
    name: ha
  register: ha_network_active
- name: Define Internal Network
  when: assure_libvirt_networks
  tags: networks
  virt_net:
    uri: "{{ libvirt_connect_string }}"
    autostart: yes
    command: define
    name: internal
    xml: '{{ lookup("template", "internal_network.xml.j2") }}'
  register: internal_network_defined
- name: Activate Internal Network
  when: 
    - assure_libvirt_networks
    - internal_network_defined
  tags: networks
  virt_net:
    uri: "{{ libvirt_connect_string }}"
    command: start
    state: active
    name: internal
  register: internal_network_active
- name: Define External Network
  when: assure_libvirt_networks
  tags: networks
  virt_net:
    uri: "{{ libvirt_connect_string }}"
    autostart: yes
    command: define
    name: external
    xml: '{{ lookup("template", "external_network.xml.j2") }}'
  register: external_network_defined
- name: Activate External Network
  when: 
    - assure_libvirt_networks
    - external_network_defined
  tags: networks
  virt_net:
    uri: "{{ libvirt_connect_string }}"
    command: start
    state: active
    name: external
  register: external_network_active