---
# create instance
- name: Disk Image Folder
  when:
    - assure_guest
    - configdrive_copied
    - state == "running"
  tags: guest
  become: yes
  file:
    path: "{{ tmos_disk_image_folder }}" 
    state: directory
    recurse: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  register: tmos_disk_image_directory
- name: Check Existing VE Disk Image
  when:
    - assure_guest
    - tmos_disk_image_directory
    - state == "running"
  stat:
    path: "{{ tmos_disk_image_folder }}/{{ guest_uuid }}.qcow2"
  register: ve_image_stat
- name: Check Local TMOS LTM Disk Image
  when: 
    - assure_guest
    - tmos_disk_image_directory
    - guest_type == "ltm"
    - state == "running"
    - ve_image_stat.stat.exists == false
  tags: guest
  local_action: stat path="{{ tmos_ltm_image }}"
  register: ltm_available
- name: Copy TMOS LTM Disk Image
  when: 
    - assure_guest
    - guest_type == "ltm"
    - ltm_available
    - state == "running"
    - ve_image_stat.stat.exists == false
  copy:
    src: "{{ tmos_ltm_image }}"
    dest: "{{ tmos_disk_image_folder }}/{{ guest_uuid }}.qcow2"
    mode: '0644'
  register: image_copied
- name: Check Local TMOS ALL Disk Image
  when: 
    - assure_guest
    - tmos_disk_image_directory
    - guest_type == "all"
    - state == "running"
    - ve_image_stat.stat.exists == false
  tags: guest
  local_action: stat path="{{ tmos_all_image }}"
  register: all_available
- name: Copy TMOS ALL Disk Image
  when:
    - assure_guest
    - guest_type == "all"
    - all_available
    - state == "running"
    - ve_image_stat.stat.exists == false
  copy:
    src: "{{ tmos_all_image }}"
    dest: "{{ tmos_disk_image_folder }}/{{ guest_uuid }}.qcow2"
    force: no
    mode: '0644'
  register: image_copied
- name: Resize TMOS Disk Image
  when:
    - assure_guest
    - state == "running"
    - image_copied
  become: yes
  command: "qemu-img resize {{ tmos_disk_image_folder }}/{{ guest_uuid }}.qcow2 +{{ guest_disk_image_size }}G"
  register: disk_resized
- name: TMOS Define 4NIC Virtual Edition Instance
  when: 
    - assure_guest
    - network_mode == "routed"
    - state == "running"
    - guest_nic_count == 4
    - configdrive_copied
  tags: guest
  virt:
    uri: "{{ libvirt_connect_string }}"
    command: define
    name: "{{ guest_uuid }}"
    xml: "{{ lookup('template', 'domain_4_nic_routed.xml.j2') }}"
  register: domain_defined
- name: TMOS Define 4NIC Virtual Edition Instance
  when: 
    - assure_guest
    - network_mode == "bridged"
    - state == "running"
    - guest_nic_count == 4
    - configdrive_copied
  tags: guest
  virt:
    uri: "{{ libvirt_connect_string }}"
    command: define
    name: "{{ guest_uuid }}"
    xml: "{{ lookup('template', 'domain_4_nic_bridged.xml.j2') }}"
  register: domain_defined
- name: TMOS Define 3NIC Virtual Edition Instance
  when: 
    - assure_guest
    - network_mode == "routed"
    - state == "running"
    - guest_nic_count == 3
    - configdrive_copied
  tags: guest
  virt:
    uri: "{{ libvirt_connect_string }}"
    command: define
    name: "{{ guest_uuid }}"
    xml: "{{ lookup('template', 'domain_3_nic_routed.xml.j2') }}"
  register: domain_defined
- name: TMOS Define 3NIC Virtual Edition Instance
  when: 
    - assure_guest
    - network_mode == "bridged"
    - state == "running"
    - guest_nic_count == 3
    - configdrive_copied
  tags: guest
  virt:
    uri: "{{ libvirt_connect_string }}"
    command: define
    name: "{{ guest_uuid }}"
    xml: "{{ lookup('template', 'domain_3_nic_bridged.xml.j2') }}"
  register: domain_defined
- name: TMOS Define 2NIC Virtual Edition Instance
  when: 
    - assure_guest
    - network_mode == "routed"
    - state == "running"
    - guest_nic_count == 2
    - configdrive_copied
  tags: guest
  virt:
    uri: "{{ libvirt_connect_string }}"
    command: define
    name: "{{ guest_uuid }}"
    xml: "{{ lookup('template', 'domain_2_nic_routed.xml.j2') }}"
  register: domain_defined
- name: TMOS Define 2NIC Virtual Edition Instance
  when: 
    - assure_guest
    - network_mode == "bridged"
    - state == "running"
    - guest_nic_count == 2
    - configdrive_copied
  tags: guest
  virt:
    uri: "{{ libvirt_connect_string }}"
    command: define
    name: "{{ guest_uuid }}"
    xml: "{{ lookup('template', 'domain_2_nic_bridged.xml.j2') }}"
  register: domain_defined
- name: TMOS Define 1NIC Virtual Edition Instance
  when: 
    - assure_guest
    - state == "running"
    - guest_nic_count == 1
    - configdrive_copied
  tags: guest
  virt:
    uri: "{{ libvirt_connect_string }}"
    command: define
    name: "{{ guest_uuid }}"
    xml: "{{ lookup('template', 'domain_1_nic.xml.j2') }}"
  register: domain_defined
- name: Clean up Domain Template
  when: 
    - assure_guest
    - domain_defined
  local_action: "file path=./{{ guest_uuid }}.xml state=absent"
- name: TMOS Virtual Edition Instance
  when: 
    - assure_guest
    - domain_defined
  tags: guest
  virt:
    uri: "{{ libvirt_connect_string }}"
    state: "{{ state }}"
    name: "{{ guest_uuid }}"
  ignore_errors: yes
  register: ve_in_state
- name: TMOS Virtual Edition Clean Up
  when: 
    - assure_guest
    - ve_in_state
    - state == 'destroyed'
  tags: guest
  ignore_errors: yes
  virt:
    uri: "{{ libvirt_connect_string }}"
    command: undefine
    name: "{{ guest_uuid }}"
  register: ve_undefined
- name: TMOS Virtual Edition Folder Clean Up
  when: 
    - assure_guest
    - ve_undefined
    - state == 'destroyed'
  tags: guest
  file:
    path: "{{ tmos_domain_folder }}"
    state: absent
  register: ve_deleted
