#cloud-config
chpasswd:
  expire: false
  list: |
    root:$root_password
    admin:$admin_password
tmos_static_mgmt:
  enabled: true
  icontrollx_trusted_sources: false
  icontrollx_package_urls:
    - $do_url
    - $as3_url
  ip: $mgmt_cidr
  gw: $mgmt_gw
  mtu: $mgmt_mtu
  hostname: $hostname
  nameservers: [ $nameservers ]
  searchdomain: $searchdomain
  ntpservers: [ $ntpservers ]
  phone_home_url: "$phone_home_url"
  phone_home_cli: "$wc_notify"
  post_onboard_enabled: false
bootcmd:
  - "printf \"platform=Z100\\nfamily=0xC000000\\nhost=Z100\\nsystype=0x71\\n\">/PLATFORM"