#cloud-config
chpasswd:
  expire: false
  list: |
    root:{{ tmos_root_password }}
    admin:{{ tmos_admin_password }}
tmos_configdrive_openstack:
  enabled: true
  rd_enabled: false
  configsync_interface: 1.1
  default_route_interface: 1.1
  inject_routes: true
  icontrollx_trusted_sources: false
  icontrollx_package_urls:
    - {{ do_url }}
    - {{ as3_url }}
  do_enabled: true
  do_declaration:
    schemaVersion: 1.0.0
    class: Device
    async: true
    label: Cloudinit Onboarding
    Common:
      class: Tenant
      provisioningLevels:
        class: Provision
        ltm: nominal
      poolLicense:
        class: License
        licenseType: licensePool
        bigIqHost: {{ license_host }}
        bigIqUsername: {{ license_username }}
        bigIqPassword: {{ license_password }}
        licensePool: {{ license_pool }}
        reachable: false
        hypervisor: kvm
      dbvars:
        class: DbVariables
        ui.advisory.enabled: true
        ui.advisory.color: orange
        ui.advisory.text: This device is under centralized management.
  as3_enabled: false
  phone_home_url: "{{ phone_home_url }}"
  post_onboard_enabled: false
bootcmd:
  - "printf \"platform=Z100\\nfamily=0xC000000\\nhost=Z100\\nsystype=0x71\\n\">/PLATFORM"
